name: PR Request Checks

on:
  pull_request:
    types: ["opened", "synchronize", "auto_merge_enabled"]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: terraform validate
        run: |
          terraform init
          terraform validate
